	<article>
		<h3 class="">Oops!</h3>
		<section class="">
	    	<span class="">4</span>
	    	<i class="icon-cirlce-big-c1">
	        	<img src="" alt="0">
	    	</i>
	    	<span class="">4</span>
		</section>
		<h1 class="">You are lost...</h1>
	    <section class="">
	        <div class="container">
	            <div class="">
	                <h2>Page not found</h2>
	                <p>You have stumbled on an unbeaten track!</p>
	            </div>

	            <div class="section-actions">
	                <a href="/" class="" tabindex="0">Back to the home page</a>
	            </div>
	        </div>
	    </section>
	</article>
