<?php
/**
 * @template: Script
 * @usage: Loading js files
 *
 * Google recaptcha key 
 * @var string $recaptchaKey
 */
?>

<script id="google" src="https://www.google.com/recaptcha/api.js?render=<?= $recaptchaKey; ?>" async></script>
	<!-- <script src="../public/js/initReview.js"></script> -->
	<!-- <script src="../public/js/initAnalytic.js"></script> -->
	<!-- <script src="../public/js/initForm.js"></script> -->
<script src="/public/js/main.js"></script>

